### ISSUE TITLE
Fails to build on Linux

### ISSUE THREAD

**Issue by gnzlbg** [gnzlbg/sleef-sys#1]
cc @alexcrichton have you seen this one before?

https://travis-ci.org/gnzlbg/sleef-sys/jobs/415654397#L1208 

= note: /usr/bin/ld: /home/travis/build/gnzlbg/sleef-sys/target/x86_64-unknown-linux-gnu/debug/deps/libsleef_sys-8a15d552e254890c.rlib(dispsse.c.o): relocation R_X86_64_32S against `Sleef_sind2_u35sse2' can not be used when making a shared object; recompile with -fPIC
          /home/travis/build/gnzlbg/sleef-sys/target/x86_64-unknown-linux-gnu/debug/deps/libsleef_sys-8a15d552e254890c.rlib: error adding symbols: Bad value
          collect2: error: ld returned 1 exit status

**Comment by alexcrichton** [comment]
@gnzlbg ah looks like `dispsse.c` isn't compiled with `-fPIC` maybe, is that part of the native build here and maybe a flag was forgotten?

**Comment by gnzlbg** [comment]
So now it is building, and I have a branch of rust-bindgen that supports vector types and makes this work correctly and the tests actually pass instead of just returning garbage.
